### PR TITLE
Merge Docs & Tools and Website WGs into Ecosystem WG

### PR DESCRIPTION
**Pull request by ckerr**
As discussed at the NYC Maintainers' summit and in last week's website WG meeting, these two groups have a lot of domain and membership overlap. This PR merges them into a single WG.

## Decisions to be made by the WG (made in 2019-09-26 meeting)

Meetings: biweekly. First meeting is Thursday, October 10 at 9 AM PT
Chair: @malept 
Mission statement: "Oversees the projects that make Electron app development easier."
Name: "Ecosystem WG"

## TODO
 - [x] Solicit consensus from the other WGs to ratify the change (@ckerr) DONE: added to all WGs' meeting agendas
 - [ ] After ratification, ask Community & Safety to update Slack:
   - [ ] Create a new channel, #wg-tbd
   - [ ] Add all the #wg-docs-tools and #wg-website members
   - [ ] Archive #wg-docs-tools
   - [ ] Archive #wg-website
 - [ ] After ratification, update calendar meetings
 - [ ] After ratification, update [website](https://electronjs.org/governance)

### CODE REVIEW

**Comment by ckerr** [comment]
@electron/wg-docs-tools @electron/wg-website

**Comment by groundwater** [comment]
👍 for _Docs & Tools & Website_ because it's one less code name I have to keep in my head.

**Comment by malept** [comment]
:bike: :derelict_house: The pedantic part of my brain wants there to only be one ampersand in the proposed WG name: Docs, Tools, & Website WG

**Comment by ckerr** [comment]
It's just so prolix though. I'm currently rooting for something more like "stack" though that needs work, too.

**Comment by zeke** [comment]
> prolix

TIL: https://en.wiktionary.org/wiki/prolix

**Pull request merged**
